version: '3.9'

services:
  app:
    container_name: app-sigrh
    image: sigrh
    restart: always
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
      - '3000:3000'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssqlSigrh
    environment:
      - SA_PASSWORD=${DB_PASSWORD:-P4ssw0rd}
      - ACCEPT_EULA=Y
      - Encrypt=no
    volumes:
      - ./docker/MSSQL:/var/opt/mssqlSigrh/data
      - ./docker/MSSQL/log:/var/opt/mssqlSigrh/log
      - ./docker/MSSQL/secrets:/var/opt/mssqlSigrh/secrets
    ports:
      - '1433:1433'
